name: Build Docker Images, Scan, and Run
on:
  push:
    branches:
      - main
jobs:
  build-scan-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java, Maven, Node.js
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "17"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
     
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.20.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
     
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Kubectl Action
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment-service.yml -n mygithub
      - name: Check Kubernetes Services
        run: |
          kubectl get svc -n mygithub
